// Code generated by gen-vo. DO NOT EDIT.
package chat

func (id ThreadID) Value() string {
	return id.value
}

func (id ThreadID) Equals(other ThreadID) bool {
	return id.value == other.value
}

func (id ThreadID) String() string {
	return id.value
}

