// Code generated by gen-vo. DO NOT EDIT.
package chat

func (id ThreadMessageID) Value() string {
	return id.value
}

func (id ThreadMessageID) Equals(other ThreadMessageID) bool {
	return id.value == other.value
}

func (id ThreadMessageID) String() string {
	return id.value
}

