// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service/v1/local.proto

package servicev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/handlename/otomo/internal/proto/entity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalGetReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *v1.Prompt             `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalGetReplyRequest) Reset() {
	*x = LocalGetReplyRequest{}
	mi := &file_service_v1_local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalGetReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalGetReplyRequest) ProtoMessage() {}

func (x *LocalGetReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalGetReplyRequest.ProtoReflect.Descriptor instead.
func (*LocalGetReplyRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_local_proto_rawDescGZIP(), []int{0}
}

func (x *LocalGetReplyRequest) GetPrompt() *v1.Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

type LocalGetReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *v1.Answer             `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalGetReplyResponse) Reset() {
	*x = LocalGetReplyResponse{}
	mi := &file_service_v1_local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalGetReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalGetReplyResponse) ProtoMessage() {}

func (x *LocalGetReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalGetReplyResponse.ProtoReflect.Descriptor instead.
func (*LocalGetReplyResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_local_proto_rawDescGZIP(), []int{1}
}

func (x *LocalGetReplyResponse) GetAnswer() *v1.Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

var File_service_v1_local_proto protoreflect.FileDescriptor

const file_service_v1_local_proto_rawDesc = "" +
	"\n" +
	"\x16service/v1/local.proto\x12\n" +
	"service.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16entity/v1/answer.proto\x1a\x16entity/v1/prompt.proto\"J\n" +
	"\x14LocalGetReplyRequest\x122\n" +
	"\x06prompt\x18\x01 \x01(\v2\x11.entity.v1.PromptB\a\xbaH\x04r\x02\x10\x01R\x06prompt\"B\n" +
	"\x15LocalGetReplyResponse\x12)\n" +
	"\x06answer\x18\x01 \x01(\v2\x11.entity.v1.AnswerR\x06answer2Z\n" +
	"\x05Local\x12Q\n" +
	"\bGetReply\x12 .service.v1.LocalGetReplyRequest\x1a!.service.v1.LocalGetReplyResponse\"\x00B\xa6\x01\n" +
	"\x0ecom.service.v1B\n" +
	"LocalProtoP\x01Z?github.com/handlename/otomo/internal/proto/service/v1;servicev1\xa2\x02\x03SXX\xaa\x02\n" +
	"Service.V1\xca\x02\n" +
	"Service\\V1\xe2\x02\x16Service\\V1\\GPBMetadata\xea\x02\vService::V1b\x06proto3"

var (
	file_service_v1_local_proto_rawDescOnce sync.Once
	file_service_v1_local_proto_rawDescData []byte
)

func file_service_v1_local_proto_rawDescGZIP() []byte {
	file_service_v1_local_proto_rawDescOnce.Do(func() {
		file_service_v1_local_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v1_local_proto_rawDesc), len(file_service_v1_local_proto_rawDesc)))
	})
	return file_service_v1_local_proto_rawDescData
}

var file_service_v1_local_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_v1_local_proto_goTypes = []any{
	(*LocalGetReplyRequest)(nil),  // 0: service.v1.LocalGetReplyRequest
	(*LocalGetReplyResponse)(nil), // 1: service.v1.LocalGetReplyResponse
	(*v1.Prompt)(nil),             // 2: entity.v1.Prompt
	(*v1.Answer)(nil),             // 3: entity.v1.Answer
}
var file_service_v1_local_proto_depIdxs = []int32{
	2, // 0: service.v1.LocalGetReplyRequest.prompt:type_name -> entity.v1.Prompt
	3, // 1: service.v1.LocalGetReplyResponse.answer:type_name -> entity.v1.Answer
	0, // 2: service.v1.Local.GetReply:input_type -> service.v1.LocalGetReplyRequest
	1, // 3: service.v1.Local.GetReply:output_type -> service.v1.LocalGetReplyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_v1_local_proto_init() }
func file_service_v1_local_proto_init() {
	if File_service_v1_local_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_local_proto_rawDesc), len(file_service_v1_local_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_local_proto_goTypes,
		DependencyIndexes: file_service_v1_local_proto_depIdxs,
		MessageInfos:      file_service_v1_local_proto_msgTypes,
	}.Build()
	File_service_v1_local_proto = out.File
	file_service_v1_local_proto_goTypes = nil
	file_service_v1_local_proto_depIdxs = nil
}
