[tasks.init]
description = "Initialize Terraform"
run = "terraform init"

[tasks.plan]
description = "Show Terraform changes"
depends = ["init"]
run = "bash -c 'set -o pipefail; terraform plan -parallelism=90 | egrep -v \"(Refreshing state...|Reading...|Read complete after)\"'"

[tasks.apply]
description = "Apply Terraform changes"
depends = ["init"]
run = "terraform apply -parallelism=90"

[tasks.lock]
description = "Generate/Update provider lock file"
run = """
terraform init -upgrade
terraform providers lock \
  -platform=linux_amd64 \
  -platform=linux_arm64 \
  -platform=darwin_amd64 \
  -platform=darwin_arm64
"""
