// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: entity/v1/answer.proto

package entityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Cost          float32                `protobuf:"fixed32,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_entity_v1_answer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_entity_v1_answer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_entity_v1_answer_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Answer) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_entity_v1_answer_proto protoreflect.FileDescriptor

const file_entity_v1_answer_proto_rawDesc = "" +
	"\n" +
	"\x16entity/v1/answer.proto\x12\tentity.v1\"6\n" +
	"\x06Answer\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x02R\x04costB\xa0\x01\n" +
	"\rcom.entity.v1B\vAnswerProtoP\x01Z=github.com/handlename/otomo/internal/proto/entity/v1;entityv1\xa2\x02\x03EXX\xaa\x02\tEntity.V1\xca\x02\tEntity\\V1\xe2\x02\x15Entity\\V1\\GPBMetadata\xea\x02\n" +
	"Entity::V1b\x06proto3"

var (
	file_entity_v1_answer_proto_rawDescOnce sync.Once
	file_entity_v1_answer_proto_rawDescData []byte
)

func file_entity_v1_answer_proto_rawDescGZIP() []byte {
	file_entity_v1_answer_proto_rawDescOnce.Do(func() {
		file_entity_v1_answer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_v1_answer_proto_rawDesc), len(file_entity_v1_answer_proto_rawDesc)))
	})
	return file_entity_v1_answer_proto_rawDescData
}

var file_entity_v1_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_v1_answer_proto_goTypes = []any{
	(*Answer)(nil), // 0: entity.v1.Answer
}
var file_entity_v1_answer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_v1_answer_proto_init() }
func file_entity_v1_answer_proto_init() {
	if File_entity_v1_answer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_v1_answer_proto_rawDesc), len(file_entity_v1_answer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_v1_answer_proto_goTypes,
		DependencyIndexes: file_entity_v1_answer_proto_depIdxs,
		MessageInfos:      file_entity_v1_answer_proto_msgTypes,
	}.Build()
	File_entity_v1_answer_proto = out.File
	file_entity_v1_answer_proto_goTypes = nil
	file_entity_v1_answer_proto_depIdxs = nil
}
