package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type VOInfo struct {
	Name      string
	FieldType string
}

func main() {
	fileName := flag.String("file", "", "Target file name to parse")
	flag.Parse()

	if *fileName == "" {
		fmt.Println("Error: -file is required")
		os.Exit(1)
	}

	if err := runGenerator(*fileName); err != nil {
		fmt.Printf("Generator error: %v\n", err)
		os.Exit(1)
	}
}

func hasVOCorrespondingComment(commentGroup *ast.CommentGroup) bool {
	if commentGroup == nil {
		return false
	}
	for _, comment := range commentGroup.List {
		if strings.Contains(comment.Text, "@vo") {
			return true
		}
	}
	return false
}

func runGenerator(fileName string) error {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, fileName, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parsing target file: %w", err)
	}

	var vos []VOInfo
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			isVO := hasVOCorrespondingComment(genDecl.Doc) ||
				hasVOCorrespondingComment(typeSpec.Doc) ||
				hasVOCorrespondingComment(typeSpec.Comment)

			if !isVO {
				continue
			}

			var fieldType string
			for _, field := range structType.Fields.List {
				if len(field.Names) == 1 && field.Names[0].Name == "value" {
					var typeBuf bytes.Buffer
					if err := printer.Fprint(&typeBuf, fset, field.Type); err == nil {
						fieldType = typeBuf.String()
					}
				}
			}

			if fieldType == "" {
				continue
			}

			if fieldType != "string" {
				fmt.Fprintf(os.Stderr, "Warning: struct %s is marked as @vo but its 'value' field is of type %s (must be string)\n", typeSpec.Name.Name, fieldType)
				continue
			}

			vos = append(vos, VOInfo{
				Name:      typeSpec.Name.Name,
				FieldType: fieldType,
			})
		}
	}

	if len(vos) == 0 {
		return nil
	}

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("// Code generated by gen-vo. DO NOT EDIT.\npackage %s\n\n", node.Name.Name))

	const tmpl = `{{range .}}func (id {{.Name}}) Value() {{.FieldType}} {
	return id.value
}

func (id {{.Name}}) Equals(other {{.Name}}) bool {
	return id.value == other.value
}

func (id {{.Name}}) String() string {
	return id.value
}

{{end}}`

	t := template.Must(template.New("vo").Parse(tmpl))
	if err := t.Execute(&buf, vos); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	ext := filepath.Ext(fileName)
	base := strings.TrimSuffix(fileName, ext)
	outFileName := base + "_gen.go"

	return os.WriteFile(outFileName, buf.Bytes(), 0644)
}
