// Code generated by gen-vo. DO NOT EDIT.
package reasoning

func (id ToolCallID) Value() string {
	return id.value
}

func (id ToolCallID) Equals(other ToolCallID) bool {
	return id.value == other.value
}

func (id ToolCallID) String() string {
	return id.value
}

func (id ToolName) Value() string {
	return id.value
}

func (id ToolName) Equals(other ToolName) bool {
	return id.value == other.value
}

func (id ToolName) String() string {
	return id.value
}
