// Code generated by gen-vo. DO NOT EDIT.
package core

func (id UserID) Value() string {
	return id.value
}

func (id UserID) Equals(other UserID) bool {
	return id.value == other.value
}

func (id UserID) String() string {
	return id.value
}

func (id ChannelID) Value() string {
	return id.value
}

func (id ChannelID) Equals(other ChannelID) bool {
	return id.value == other.value
}

func (id ChannelID) String() string {
	return id.value
}

func (id MessageID) Value() string {
	return id.value
}

func (id MessageID) Equals(other MessageID) bool {
	return id.value == other.value
}

func (id MessageID) String() string {
	return id.value
}
